title: Windows codecs
email: entoyukari@gmail.com
description: >- 
  Windows codecs.
  japan
baseurl: "https://ygsiro.github.io/windows-codecs"
url: "https://ygsiro.github.io"
twitter_username: yg_siro
github_username:  ygsiro

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true